# Generated by Django 6.0.3 on 2026-04-05 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('KOR', '한식'), ('CHI', '중식'), ('JPN', '일식'), ('WES', '양식'), ('DES', '디저트'), ('ETC', '기타')], default='KOR', max_length=3)),
                ('location', models.CharField(choices=[('SB', '성북구'), ('GD', '강동구'), ('GN', '강남구'), ('YS', '용산구'), ('SEO', '서울기타')], default='SEO', max_length=3)),
                ('address', models.CharField(help_text='상세 주소를 입력하세요', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='restaurants/')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='restaurants.restaurant')),
            ],
        ),
    ]
