# Generated by Django 6.0.3 on 2026-04-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_alter_restaurant_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='category',
            field=models.CharField(choices=[('KOR', '한식'), ('CHI', '중식'), ('JPN', '일식'), ('WES', '양식'), ('DES', '디저트'), ('ETC', '기타')], default='KOR', max_length=10),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='location',
            field=models.CharField(choices=[('SEOUL', '서울'), ('GYEONGGI', '경기'), ('INCHEON', '인천'), ('BUSAN', '부산'), ('DAEGU', '대구'), ('DAEJEON', '대전'), ('GWANGJU', '광주'), ('ULSAN', '울산'), ('SEJONG', '세종'), ('GANGWON', '강원'), ('CHUNGBUK', '충북'), ('CHUNGNAM', '충남'), ('JEONBUK', '전북'), ('JEONNAM', '전남'), ('GYEONGBUK', '경북'), ('GYEONGNAM', '경남'), ('JEJU', '제주'), ('ETC', '기타')], default='SEOUL', max_length=20),
        ),
    ]
