# Generated by Django 6.0.3 on 2026-04-25 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_restaurant_author_bucketlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='category',
            field=models.CharField(choices=[('KOR', '한식'), ('CHI', '중식'), ('JPN', '일식'), ('WES', '양식'), ('DES', '디저트'), ('MEAT', '고기/구이'), ('BAR', '술집'), ('ETC', '기타')], default='KOR', max_length=10),
        ),
        migrations.DeleteModel(
            name='BucketList',
        ),
    ]
