# Generated by Django 6.0.3 on 2026-04-25 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_restaurant_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(choices=[(1, '⭐ 1점'), (2, '⭐⭐ 2점'), (3, '⭐⭐⭐ 3점'), (4, '⭐⭐⭐⭐ 4점'), (5, '⭐⭐⭐⭐⭐ 5점')], default=5),
        ),
    ]
