# Generated by Django 6.0.3 on 2026-04-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_comment_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, '⭐ 1점'), (2, '⭐⭐ 2점'), (3, '⭐⭐⭐ 3점'), (4, '⭐⭐⭐⭐ 4점'), (5, '⭐⭐⭐⭐⭐ 5점')], null=True),
        ),
    ]
